--- #YAML:1.0
name:                Tk-SMListbox
version:             1.11
abstract:            Multi-Listbox Widget with Sort Indicators
license:             ~
author:              
    - Jim Turner
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Tk:                            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
